# -*- coding: utf-8 -*-
"""ShifaMind_v2.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwNMcpjy9rbmi0iBULUzJGTMTreaaeiD

# P1

## Analyze
"""

"""
analyze_codes_concepts.py — ShifaMind v2.1 Pre-Training Analysis

Run this in Colab BEFORE retraining. It will:
  1. Find replacement ICD-10 codes for the 3 worst performers (Y929, Y92230, Z20822)
  2. Analyze concept coverage for all 50 ICD codes
  3. Identify concept gaps and suggest additions
  4. Output the final v2.1 ICD code list and concept list to Drive

Outputs → /content/drive/MyDrive/ShifaMind_v2.1/analysis/
"""

# ============================================================================
# IMPORTS & SETUP
# ============================================================================

import json
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter, defaultdict

try:
    from google.colab import drive
    drive.mount("/content/drive")
    print("Google Drive mounted.")
except ModuleNotFoundError:
    print("Not in Colab — skipping mount.")

# Paths
DRIVE_RAW      = Path("/content/drive/MyDrive/ShifaMind/01_Raw_Datasets/Extracted")
DIAGNOSES_CSV  = DRIVE_RAW / "mimic-iv-3.1/mimic-iv-3.1/hosp/diagnoses_icd.csv.gz"
V2_DATA_DIR    = Path("/content/drive/MyDrive/ShifaMind_v2/data")
OUT_DIR        = Path("/content/drive/MyDrive/ShifaMind_v2.1/analysis")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================================
# PART 1: FIND REPLACEMENT ICD-10 CODES
# ============================================================================

print("\n" + "=" * 70)
print("PART 1: Finding replacement ICD-10 codes")
print("=" * 70)

# Current top-50 codes (from v2 training)
CURRENT_TOP_50 = [
    "E785", "I10", "Z87891", "K219", "F329", "E039", "Z794", "I2510",
    "J449", "F419", "E119", "Z20822", "Z7901", "F17210", "E669", "G4733",
    "D649", "Z7902", "Y929", "E1122", "D62", "N179", "I4891", "J45909",
    "Z66", "E871", "E872", "I480", "Z8673", "N390", "I129", "G8929",
    "Z86718", "N189", "I5032", "I130", "I110", "N400", "J9601", "Z955",
    "Z951", "D696", "K5900", "E1165", "M109", "D509", "G4700", "Z515",
    "Y92230", "I252",
]

# Codes to remove (worst performers — all non-clinical)
CODES_TO_REMOVE = {"Y929", "Y92230", "Z20822"}

print(f"\nCodes to remove (non-clinical / zero signal):")
print(f"  Y929   — Unspecified place of occurrence (F1=0.33)")
print(f"  Y92230 — Hospital as place of occurrence (F1=0.28)")
print(f"  Z20822 — Contact with COVID-19 exposure  (F1=0.00)")

# Load full diagnosis data to find replacements
print(f"\nLoading diagnoses_icd.csv.gz …")
df_dx = pd.read_csv(DIAGNOSES_CSV, compression="gzip")
df_dx10 = df_dx[df_dx["icd_version"] == 10].copy()
df_dx10_unique = df_dx10.drop_duplicates(subset=["hadm_id", "icd_code"])

# Full frequency ranking
code_counts = df_dx10_unique["icd_code"].value_counts()
print(f"  Total unique ICD-10 codes: {len(code_counts):,}")

# Find ranks of current codes
current_set = set(CURRENT_TOP_50)
print(f"\n  Ranks of codes being removed:")
for code in CODES_TO_REMOVE:
    rank = list(code_counts.index).index(code) + 1
    count = code_counts[code]
    print(f"    {code}: rank #{rank}, count = {count:,}")

# Find candidate replacements (codes NOT in current top-50)
print(f"\n  Next available codes after current top-50:")
candidates = []
shown = 0
for i, (code, count) in enumerate(code_counts.items()):
    rank = i + 1
    if code not in current_set:
        # Skip Y-codes and Z20-Z29 (external cause / contact/exposure — same issues)
        # Also skip codes starting with V, W, X (external causes of morbidity)
        skip = False
        if code.startswith(("V", "W", "X", "Y")):
            skip = True
        # Z20-Z29 are "contact with" codes — administrative, not clinical
        if code.startswith("Z2") and len(code) >= 3 and code[2].isdigit() and int(code[1:3]) >= 20 and int(code[1:3]) <= 29:
            skip = True

        candidates.append({
            "rank": rank,
            "icd_code": code,
            "count": int(count),
            "skipped": skip,
            "skip_reason": "External cause / contact code" if skip else "",
        })
        shown += 1
        if shown <= 20:
            flag = " ← SKIP (external/contact)" if skip else " ✓ CANDIDATE"
            print(f"    Rank #{rank}: {code:>10s}  count={count:>7,}{flag}")
    if shown >= 20:
        break

# Select top 3 non-skipped candidates
replacements = [c for c in candidates if not c["skipped"]][:3]
print(f"\n  Selected replacements:")
for r in replacements:
    print(f"    {r['icd_code']:>10s}  (rank #{r['rank']}, count={r['count']:,})")

# Build new top-50 code list
new_top_50 = [c for c in CURRENT_TOP_50 if c not in CODES_TO_REMOVE]
for r in replacements:
    new_top_50.append(r["icd_code"])

assert len(new_top_50) == 50, f"Expected 50 codes, got {len(new_top_50)}"

# ============================================================================
# Build the new top50_icd10_info structure
# ============================================================================

new_top50_counts = {}
for code in new_top_50:
    new_top50_counts[code] = int(code_counts.get(code, 0))

# Also need to know which hadm_ids have discharge notes
# Load discharge notes to compute final admission count
print(f"\n  Loading discharge notes to compute final admission count …")
DISCHARGE_CSV = DRIVE_RAW / "mimic-iv-note-2.2/note/discharge.csv.gz"
df_notes = pd.read_csv(DISCHARGE_CSV, compression="gzip", usecols=["hadm_id"])
df_notes["hadm_id"] = df_notes["hadm_id"].astype(int)
note_hadm_ids = set(df_notes["hadm_id"].unique())

# Count admissions that have at least one new top-50 code AND a discharge note
top50_set = set(new_top_50)
dx_in_top50 = df_dx10_unique[df_dx10_unique["icd_code"].isin(top50_set)]
hadm_with_top50 = set(dx_in_top50["hadm_id"].astype(int).unique())
hadm_final = hadm_with_top50 & note_hadm_ids

print(f"  Admissions with ≥1 new top-50 code AND discharge note: {len(hadm_final):,}")

new_top50_info = {
    "total_admissions_in_diagnoses": int(df_dx10["hadm_id"].nunique()),
    "total_admissions_final": len(hadm_final),
    "top_50_codes": new_top_50,
    "top_50_counts": new_top50_counts,
    "replaced_codes": {
        "removed": list(CODES_TO_REMOVE),
        "added": [r["icd_code"] for r in replacements],
        "reason": "Y929/Y92230 are external-cause location codes with no clinical "
                  "text signal. Z20822 (COVID exposure) has zero F1 — likely due to "
                  "inconsistent documentation patterns across pandemic waves.",
    },
}


# ============================================================================
# PART 2: ICD-10 CODE → CONCEPT COVERAGE ANALYSIS
# ============================================================================

print("\n" + "=" * 70)
print("PART 2: Concept coverage analysis")
print("=" * 70)

# Current 111 concepts
CURRENT_CONCEPTS = [
    "fever", "cough", "dyspnea", "pain", "nausea", "vomiting", "diarrhea", "fatigue",
    "headache", "dizziness", "weakness", "confusion", "syncope", "chest", "abdominal",
    "dysphagia", "hemoptysis", "hematuria", "hematemesis", "melena", "jaundice",
    "edema", "rash", "pruritus", "weight", "anorexia", "malaise",
    "hypotension", "hypertension", "tachycardia", "bradycardia", "tachypnea", "hypoxia",
    "hypothermia", "shock", "altered", "lethargic", "obtunded",
    "cardiac", "pulmonary", "renal", "hepatic", "neurologic", "gastrointestinal",
    "respiratory", "cardiovascular", "genitourinary", "musculoskeletal", "endocrine",
    "hematologic", "dermatologic", "psychiatric",
    "infection", "sepsis", "pneumonia", "uti", "cellulitis", "meningitis",
    "failure", "infarction", "ischemia", "hemorrhage", "thrombosis", "embolism",
    "obstruction", "perforation", "rupture", "stenosis", "regurgitation",
    "hypertrophy", "atrophy", "neoplasm", "malignancy", "metastasis",
    "elevated", "decreased", "anemia", "leukocytosis", "thrombocytopenia",
    "hyperglycemia", "hypoglycemia", "acidosis", "alkalosis", "hypoxemia",
    "creatinine", "bilirubin", "troponin", "bnp", "lactate", "wbc", "cultures",
    "infiltrate", "consolidation", "effusion", "cardiomegaly",
    "ultrasound", "ct", "mri", "xray", "echo", "ekg",
    "antibiotics", "diuretics", "vasopressors", "insulin", "anticoagulation",
    "oxygen", "ventilation", "dialysis", "transfusion", "surgery",
]
current_concept_set = set(CURRENT_CONCEPTS)

# ============================================================================
# Clinical mapping: each ICD-10 code → concepts that SHOULD fire in notes
# This is the ground-truth clinical knowledge map.
# "existing" = concepts already in current list
# "missing"  = concepts NOT in current list but clinically important
# ============================================================================

ICD_CONCEPT_MAP = {
    # --- Endocrine / Metabolic ------------------------------------------------
    "E785":  {"desc": "Hyperlipidemia",
              "existing": ["elevated", "cardiovascular"],
              "missing":  ["cholesterol", "lipid", "statin"]},
    "E039":  {"desc": "Hypothyroidism, unspecified",
              "existing": ["endocrine", "fatigue"],
              "missing":  ["thyroid", "hypothyroid", "levothyroxine"]},
    "E119":  {"desc": "Type 2 DM without complications",
              "existing": ["hyperglycemia", "insulin", "endocrine"],
              "missing":  ["diabetes", "diabetic", "a1c", "metformin"]},
    "E1122": {"desc": "Type 2 DM with diabetic CKD",
              "existing": ["hyperglycemia", "insulin", "creatinine", "renal"],
              "missing":  ["diabetes", "diabetic", "nephropathy"]},
    "E1165": {"desc": "Type 2 DM with hyperglycemia",
              "existing": ["hyperglycemia", "insulin"],
              "missing":  ["diabetes", "diabetic"]},
    "E669":  {"desc": "Obesity, unspecified",
              "existing": ["weight"],
              "missing":  ["obesity", "obese", "bmi"]},
    "E871":  {"desc": "Hypo-osmolality / hyponatremia",
              "existing": ["decreased"],
              "missing":  ["sodium", "hyponatremia"]},
    "E872":  {"desc": "Acidosis",
              "existing": ["acidosis"],
              "missing":  []},

    # --- Cardiovascular -------------------------------------------------------
    "I10":   {"desc": "Essential hypertension",
              "existing": ["hypertension", "cardiovascular"],
              "missing":  []},
    "I2510": {"desc": "Atherosclerotic heart disease of native coronary artery",
              "existing": ["cardiac", "ischemia", "infarction", "troponin", "ekg"],
              "missing":  ["coronary", "cath"]},
    "I252":  {"desc": "Old myocardial infarction",
              "existing": ["cardiac", "infarction", "troponin"],
              "missing":  ["coronary"]},
    "I480":  {"desc": "Paroxysmal atrial fibrillation",
              "existing": ["cardiac", "tachycardia", "anticoagulation", "ekg"],
              "missing":  ["fibrillation", "afib", "arrhythmia"]},
    "I4891": {"desc": "Unspecified atrial fibrillation",
              "existing": ["cardiac", "tachycardia", "anticoagulation", "ekg"],
              "missing":  ["fibrillation", "afib", "arrhythmia"]},
    "I5032": {"desc": "Chronic diastolic heart failure",
              "existing": ["failure", "cardiac", "edema", "bnp", "diuretics"],
              "missing":  ["ejection", "heart failure", "diastolic"]},
    "I110":  {"desc": "Hypertensive heart disease with heart failure",
              "existing": ["hypertension", "failure", "cardiac"],
              "missing":  []},
    "I129":  {"desc": "Hypertensive CKD, stage 1-4 or unspecified",
              "existing": ["hypertension", "renal", "creatinine"],
              "missing":  []},
    "I130":  {"desc": "Hypertensive heart and CKD",
              "existing": ["hypertension", "cardiac", "renal", "failure"],
              "missing":  []},

    # --- Respiratory ----------------------------------------------------------
    "J449":  {"desc": "COPD, unspecified",
              "existing": ["respiratory", "dyspnea", "cough", "oxygen"],
              "missing":  ["copd", "bronchodilator", "inhaler"]},
    "J45909":{"desc": "Unspecified asthma, uncomplicated",
              "existing": ["respiratory", "dyspnea", "cough"],
              "missing":  ["asthma", "wheezing", "inhaler"]},
    "J9601": {"desc": "Acute respiratory failure with hypoxia",
              "existing": ["respiratory", "hypoxia", "ventilation", "oxygen"],
              "missing":  []},

    # --- Neurologic / Psychiatric / Sleep -------------------------------------
    "F329":  {"desc": "Major depressive disorder, unspecified",
              "existing": ["psychiatric"],
              "missing":  ["depression", "depressed", "ssri", "antidepressant"]},
    "F419":  {"desc": "Anxiety disorder, unspecified",
              "existing": ["psychiatric"],
              "missing":  ["anxiety", "anxious"]},
    "F17210":{"desc": "Nicotine dependence, cigarettes, uncomplicated",
              "existing": [],
              "missing":  ["smoking", "tobacco", "nicotine", "cigarette"]},
    "G4733": {"desc": "Obstructive sleep apnea",
              "existing": [],
              "missing":  ["apnea", "sleep", "cpap"]},
    "G4700": {"desc": "Insomnia, unspecified",
              "existing": [],
              "missing":  ["insomnia", "sleep"]},
    "G8929": {"desc": "Other chronic pain",
              "existing": ["pain"],
              "missing":  ["chronic pain", "opioid"]},

    # --- Renal / GU -----------------------------------------------------------
    "N179":  {"desc": "Acute kidney injury, unspecified",
              "existing": ["renal", "creatinine"],
              "missing":  []},
    "N189":  {"desc": "Chronic kidney disease, unspecified",
              "existing": ["renal", "creatinine"],
              "missing":  ["ckd"]},
    "N390":  {"desc": "UTI, site not specified",
              "existing": ["uti", "infection", "cultures"],
              "missing":  []},
    "N400":  {"desc": "Benign prostatic hyperplasia",
              "existing": ["genitourinary"],
              "missing":  ["prostate", "urinary retention"]},

    # --- GI -------------------------------------------------------------------
    "K219":  {"desc": "GERD without esophagitis",
              "existing": ["gastrointestinal"],
              "missing":  ["reflux", "gerd", "ppi"]},
    "K5900": {"desc": "Constipation, unspecified",
              "existing": ["gastrointestinal"],
              "missing":  ["constipation", "bowel"]},

    # --- Hematologic ----------------------------------------------------------
    "D62":   {"desc": "Acute posthemorrhagic anemia",
              "existing": ["anemia", "hemorrhage", "transfusion"],
              "missing":  []},
    "D649":  {"desc": "Anemia, unspecified",
              "existing": ["anemia"],
              "missing":  []},
    "D509":  {"desc": "Iron deficiency anemia, unspecified",
              "existing": ["anemia"],
              "missing":  ["iron", "ferritin"]},
    "D696":  {"desc": "Thrombocytopenia, unspecified",
              "existing": ["thrombocytopenia"],
              "missing":  []},

    # --- Musculoskeletal ------------------------------------------------------
    "M109":  {"desc": "Gout, unspecified",
              "existing": ["musculoskeletal", "pain"],
              "missing":  ["gout"]},

    # --- Z-codes (status / history) -------------------------------------------
    "Z87891":{"desc": "Personal history of nicotine dependence",
              "existing": [],
              "missing":  ["smoking", "tobacco", "nicotine"]},
    "Z794":  {"desc": "Long-term use of insulin",
              "existing": ["insulin"],
              "missing":  ["diabetes", "diabetic"]},
    "Z7901": {"desc": "Long-term use of anticoagulants",
              "existing": ["anticoagulation"],
              "missing":  []},
    "Z7902": {"desc": "Long-term use of aspirin",
              "existing": ["anticoagulation"],
              "missing":  ["aspirin"]},
    "Z955":  {"desc": "Presence of coronary angioplasty implant & graft",
              "existing": ["cardiac"],
              "missing":  ["stent", "coronary"]},
    "Z951":  {"desc": "Presence of aortocoronary bypass graft",
              "existing": ["cardiac", "surgery"],
              "missing":  ["cabg", "coronary", "bypass"]},
    "Z66":   {"desc": "DNR status",
              "existing": [],
              "missing":  ["dnr", "palliative", "comfort", "hospice"]},
    "Z515":  {"desc": "Encounter for palliative care",
              "existing": [],
              "missing":  ["palliative", "hospice", "comfort"]},
    "Z86718":{"desc": "Personal history of pulmonary embolism",
              "existing": ["embolism", "thrombosis"],
              "missing":  []},
    "Z8673": {"desc": "Personal history of TIA / cerebral infarction",
              "existing": ["neurologic", "ischemia"],
              "missing":  ["stroke", "tia"]},
}

# ============================================================================
# Coverage analysis
# ============================================================================

print("\n--- Per-code concept coverage ---\n")
print(f"{'Code':<10s} {'Description':<48s} {'Exist':>5s} {'Miss':>5s}  Missing concepts")
print("-" * 120)

all_missing = Counter()
codes_with_no_existing = []
codes_with_high_gaps = []

# Include replacement codes in the analysis too
for code in new_top_50:
    if code in ICD_CONCEPT_MAP:
        info = ICD_CONCEPT_MAP[code]
        n_exist = len(info["existing"])
        n_miss  = len(info["missing"])
        for m in info["missing"]:
            all_missing[m] += 1
        miss_str = ", ".join(info["missing"]) if info["missing"] else "—"
        flag = ""
        if n_exist == 0 and n_miss > 0:
            flag = " ⚠️ NO COVERAGE"
            codes_with_no_existing.append(code)
        elif n_miss > n_exist:
            flag = " ⚡ HIGH GAP"
            codes_with_high_gaps.append(code)
        print(f"{code:<10s} {info['desc']:<48s} {n_exist:>5d} {n_miss:>5d}  {miss_str}{flag}")
    else:
        # Replacement codes — we'll add mapping later
        print(f"{code:<10s} {'(new replacement — see below)':<48s}     ?     ?  needs mapping")

# ============================================================================
# Summary of missing concepts ranked by how many codes they'd help
# ============================================================================

print(f"\n\n{'='*70}")
print("Missing concepts ranked by number of ICD codes they'd help")
print(f"{'='*70}")
print(f"\n{'Concept':<25s} {'# codes helped':>14s}  Codes")
print("-" * 90)

for concept, count in all_missing.most_common():
    helped_codes = [c for c, info in ICD_CONCEPT_MAP.items()
                    if concept in info["missing"] and c in set(new_top_50)]
    print(f"{concept:<25s} {count:>14d}  {', '.join(helped_codes)}")

print(f"\n  Codes with ZERO concept coverage: {codes_with_no_existing}")
print(f"  Codes with more gaps than coverage: {codes_with_high_gaps}")


# ============================================================================
# PART 3: BUILD OPTIMIZED CONCEPT LIST
# ============================================================================

print(f"\n\n{'='*70}")
print("PART 3: Building optimized concept list for v2.1")
print(f"{'='*70}")

# New concepts to ADD (clinically important, high-frequency in MIMIC notes)
CONCEPTS_TO_ADD = [
    # Diabetes / metabolic (helps E119, E1122, E1165, E669, Z794)
    "diabetes",       # "diabetes mellitus", "diabetic" covered by word boundary
    "diabetic",       # "diabetic ketoacidosis", "diabetic nephropathy"
    "a1c",            # HbA1c — key diabetes marker
    "metformin",      # most common diabetes drug
    "obesity",        # for E669
    "obese",          # alternate form
    "bmi",            # body mass index — frequently mentioned
    "cholesterol",    # for E785
    "lipid",          # lipid panel
    "statin",         # statin therapy — strong signal for E785
    "thyroid",        # for E039
    "sodium",         # for E871 (hyponatremia)
    "hyponatremia",   # direct concept for E871

    # Cardiovascular (helps I480, I4891, I5032, I2510, I252, Z955, Z951)
    "fibrillation",   # atrial fibrillation — I480, I4891
    "arrhythmia",     # broader cardiac rhythm concept
    "coronary",       # coronary artery disease — I2510, I252, Z955, Z951
    "stent",          # for Z955
    "cabg",           # coronary artery bypass graft — for Z951
    "ejection",       # ejection fraction — key HF marker

    # Respiratory (helps J449, J45909)
    "copd",           # for J449
    "asthma",         # for J45909
    "wheezing",       # key respiratory symptom
    "inhaler",        # treatment signal for COPD/asthma

    # Psychiatric / Neuro / Sleep (helps F329, F419, G4733, G4700)
    "depression",     # for F329
    "anxiety",        # for F419
    "apnea",          # for G4733
    "insomnia",       # for G4700
    "sleep",          # shared for G4733, G4700
    "cpap",           # treatment for sleep apnea

    # Smoking / substance (helps F17210, Z87891)
    "smoking",        # for F17210, Z87891
    "tobacco",        # alternate signal
    "nicotine",       # for nicotine dependence codes

    # GI (helps K219, K5900)
    "reflux",         # for K219 (GERD)
    "constipation",   # for K5900
    "bowel",          # bowel movement — GI signal

    # Palliative / goals of care (helps Z66, Z515)
    "palliative",     # for Z515
    "hospice",        # for Z515, Z66
    "comfort",        # "comfort measures" — Z66
    "dnr",            # do not resuscitate — Z66

    # Hematologic (helps D509)
    "iron",           # iron deficiency — D509
    "ferritin",       # iron stores marker

    # Renal
    "ckd",            # chronic kidney disease — N189

    # Musculoskeletal (helps M109)
    "gout",           # for M109

    # Cerebrovascular (helps Z8673)
    "stroke",         # for Z8673
    "tia",            # transient ischemic attack

    # Urologic (helps N400)
    "prostate",       # for N400 (BPH)

    # Medication-specific (helps Z7902)
    "aspirin",        # for Z7902

    # Additional high-value clinical concepts
    "opioid",         # opioid use — common in chronic pain notes
    "ppi",            # proton pump inhibitor — for K219
]

# Remove any that already exist in current concepts
new_concepts_to_add = [c for c in CONCEPTS_TO_ADD if c not in current_concept_set]

# Build final concept list
final_concepts = CURRENT_CONCEPTS + new_concepts_to_add

# Deduplicate (shouldn't be needed but just in case)
seen = set()
final_concepts_deduped = []
for c in final_concepts:
    if c not in seen:
        seen.add(c)
        final_concepts_deduped.append(c)
final_concepts = final_concepts_deduped

print(f"\n  Current concepts:    {len(CURRENT_CONCEPTS)}")
print(f"  New concepts added:  {len(new_concepts_to_add)}")
print(f"  Final concept count: {len(final_concepts)}")
print(f"\n  New concepts: {new_concepts_to_add}")


# ============================================================================
# PART 4: VERIFY — re-run coverage analysis with new concepts
# ============================================================================

print(f"\n\n{'='*70}")
print("PART 4: Re-checking coverage with expanded concept list")
print(f"{'='*70}")

new_concept_set = set(final_concepts)

print(f"\n{'Code':<10s} {'Description':<48s} {'Old':>4s} {'New':>4s} {'Gap':>4s}")
print("-" * 80)

remaining_gaps = {}
for code in new_top_50:
    if code in ICD_CONCEPT_MAP:
        info = ICD_CONCEPT_MAP[code]
        old_cover = len(info["existing"])
        # Count how many of the "missing" are now covered
        newly_covered = [m for m in info["missing"] if m in new_concept_set]
        still_missing = [m for m in info["missing"] if m not in new_concept_set]
        new_cover = old_cover + len(newly_covered)
        gap = len(still_missing)
        if gap > 0:
            remaining_gaps[code] = still_missing
        status = "✓" if gap == 0 else f"({', '.join(still_missing)})"
        print(f"{code:<10s} {info['desc']:<48s} {old_cover:>4d} {new_cover:>4d} {gap:>4d}  {status}")

if remaining_gaps:
    print(f"\n  Codes with remaining gaps (minor — specialized terms):")
    for code, gaps in remaining_gaps.items():
        print(f"    {code}: {gaps}")
else:
    print(f"\n  ✓ All codes have full concept coverage!")


# ============================================================================
# PART 5: DATA-DRIVEN VALIDATION — Check concept frequency in actual notes
# ============================================================================

print(f"\n\n{'='*70}")
print("PART 5: Validating new concepts against actual MIMIC notes (sample)")
print(f"{'='*70}")

import pickle, re
from tqdm.auto import tqdm

# Load a sample of training notes
with open(V2_DATA_DIR / "train_split.pkl", "rb") as f:
    df_train = pickle.load(f)

sample_size = min(10000, len(df_train))
sample_texts = df_train["text"].sample(n=sample_size, random_state=42).tolist()
print(f"\n  Checking concept frequency in {sample_size:,} training notes …")

concept_freq = {}
for concept in tqdm(final_concepts, desc="  Counting", leave=False):
    pattern = re.compile(r"\b" + re.escape(concept) + r"\b", re.IGNORECASE)
    count = sum(1 for text in sample_texts if pattern.search(str(text)))
    concept_freq[concept] = count

# Sort by frequency
sorted_freq = sorted(concept_freq.items(), key=lambda x: x[1], reverse=True)

# Print new concepts with their frequencies
print(f"\n  New concepts — frequency in {sample_size:,} training notes:")
print(f"  {'Concept':<25s} {'Count':>7s}  {'%':>6s}  Status")
print(f"  {'-'*25} {'-'*7}  {'-'*6}  {'-'*20}")

low_freq_concepts = []
for concept in new_concepts_to_add:
    freq = concept_freq.get(concept, 0)
    pct  = freq / sample_size * 100
    status = "✓ Good" if pct >= 1.0 else "⚠ Low (<1%)" if pct >= 0.1 else "✗ Very low (<0.1%)"
    if pct < 0.1:
        low_freq_concepts.append(concept)
    print(f"  {concept:<25s} {freq:>7,}  {pct:>5.1f}%  {status}")

if low_freq_concepts:
    print(f"\n  ⚠ Very low frequency concepts (consider removing): {low_freq_concepts}")
    # Remove very low frequency concepts
    final_concepts = [c for c in final_concepts if c not in set(low_freq_concepts)]
    new_concepts_to_add = [c for c in new_concepts_to_add if c not in set(low_freq_concepts)]
    print(f"  → Removed {len(low_freq_concepts)} low-frequency concepts")
    print(f"  → Final concept count: {len(final_concepts)}")


# ============================================================================
# PART 6: SAVE EVERYTHING
# ============================================================================

print(f"\n\n{'='*70}")
print("PART 6: Saving outputs")
print(f"{'='*70}")

# Save new top-50 ICD info
with open(OUT_DIR / "top50_icd10_info_v2.1.json", "w") as f:
    json.dump(new_top50_info, f, indent=2)
print(f"  Saved: top50_icd10_info_v2.1.json")

# Save new concept list
with open(OUT_DIR / "concept_list_v2.1.json", "w") as f:
    json.dump(final_concepts, f, indent=2)
print(f"  Saved: concept_list_v2.1.json  ({len(final_concepts)} concepts)")

# Save analysis report
report = {
    "codes_removed": list(CODES_TO_REMOVE),
    "codes_added": [r["icd_code"] for r in replacements],
    "codes_added_details": replacements,
    "original_concept_count": len(CURRENT_CONCEPTS),
    "new_concepts_added": new_concepts_to_add,
    "final_concept_count": len(final_concepts),
    "low_freq_removed": low_freq_concepts,
    "coverage_summary": {
        code: {
            "desc": ICD_CONCEPT_MAP[code]["desc"],
            "concepts_old": len(ICD_CONCEPT_MAP[code]["existing"]),
            "concepts_new": len(ICD_CONCEPT_MAP[code]["existing"]) +
                            len([m for m in ICD_CONCEPT_MAP[code]["missing"]
                                 if m in set(final_concepts)]),
        }
        for code in new_top_50 if code in ICD_CONCEPT_MAP
    },
}

with open(OUT_DIR / "analysis_report.json", "w") as f:
    json.dump(report, f, indent=2)
print(f"  Saved: analysis_report.json")

# Pretty print the final lists
print(f"\n\n{'='*70}")
print("FINAL SUMMARY")
print(f"{'='*70}")
print(f"\n  ICD-10 codes: {len(new_top_50)} (removed {len(CODES_TO_REMOVE)}, added {len(replacements)})")
print(f"  Concepts:     {len(final_concepts)} (was {len(CURRENT_CONCEPTS)}, added {len(new_concepts_to_add)})")
print(f"\n  Removed codes: {list(CODES_TO_REMOVE)}")
print(f"  Added codes:   {[r['icd_code'] for r in replacements]}")
print(f"\n  New concepts:  {new_concepts_to_add}")
print(f"\n  All outputs saved to: {OUT_DIR}")
print(f"\n  Next: update cell1_data.py with new codes + concepts, save to ShifaMind_v2.1/")

"""## Cell 1"""

"""
v2.1/cell1_data.py — ShifaMind v2.1 Phase 1: Data Loading & Preprocessing

Changes from v2.0:
  - Top-50 ICD codes: removed Y929, Y92230 (place-of-occurrence), Z20822
    (COVID exposure); replaced with E876, E875, D72829 by frequency rank
  - Concepts: 160 (was 111) — loaded from Opus analysis JSON on Drive
  - Everything generated from scratch (no files copied from v2.0)
  - Pre-tokenization (Step 9) included in this cell

Reads from:
  /content/drive/MyDrive/ShifaMind/01_Raw_Datasets/Extracted/  (MIMIC-IV)
  /content/drive/MyDrive/ShifaMind_v2.1/analysis/              (Opus outputs)

Writes to:
  /content/drive/MyDrive/ShifaMind_v2.1/data/
"""

# ============================================================================
# IMPORTS & INSTALLS
# ============================================================================

import subprocess, sys

def pip_install(*packages):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])

pip_install("transformers")

import json
import pickle
import random
import re
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

import torch
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer
from tqdm.auto import tqdm

# ============================================================================
# SEEDS
# ============================================================================

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ============================================================================
# MOUNT GOOGLE DRIVE
# ============================================================================

try:
    from google.colab import drive
    drive.mount("/content/drive")
    print("Google Drive mounted.")
except ModuleNotFoundError:
    print("Not running in Colab — skipping Drive mount.")

# ============================================================================
# PATHS
# ============================================================================

DRIVE_RAW    = Path("/content/drive/MyDrive/ShifaMind/01_Raw_Datasets/Extracted")
DIAGNOSES_CSV = DRIVE_RAW / "mimic-iv-3.1/mimic-iv-3.1/hosp/diagnoses_icd.csv.gz"
DISCHARGE_CSV = DRIVE_RAW / "mimic-iv-note-2.2/note/discharge.csv.gz"

ANALYSIS_DIR  = Path("/content/drive/MyDrive/ShifaMind_v2.1/analysis")
OUT_DIR       = Path("/content/drive/MyDrive/ShifaMind_v2.1/data")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================================
# CONFIG
# ============================================================================

MODEL_NAME = "thomas-sounack/BioClinical-ModernBERT-base"
MAX_LENGTH = 6144
TOP_N      = 50

# ICD codes that are non-clinical / structurally unpredictable from text
CODES_TO_EXCLUDE = {"Y929", "Y92230", "Z20822"}

# ============================================================================
# LOAD CONCEPT LIST FROM OPUS ANALYSIS
# ============================================================================

concept_path = ANALYSIS_DIR / "concept_list_v2.1.json"
assert concept_path.exists(), f"Missing: {concept_path}\nRun the Opus concept analysis first."

with open(concept_path) as f:
    GLOBAL_CONCEPTS = json.load(f)

# Deduplicate while preserving order
_seen, _deduped = set(), []
for c in GLOBAL_CONCEPTS:
    if c not in _seen:
        _seen.add(c)
        _deduped.append(c)
GLOBAL_CONCEPTS = _deduped
print(f"Concepts loaded from Opus analysis: {len(GLOBAL_CONCEPTS)}")

# ============================================================================
# NEGEX-STYLE NEGATION DETECTION  (identical to v2.0)
# ============================================================================

PRE_NEGATION_TRIGGERS = [
    "no evidence of", "no signs of", "no symptoms of", "no history of",
    "no longer", "negative for", "free of",
    "rules out", "ruled out",
    "did not", "does not", "was not", "were not", "is not", "are not", "cannot",
    "no", "not", "without", "denies", "denied", "denying",
    "absent", "never", "none",
    "unremarkable", "resolved", "unlikely",
]

POST_NEGATION_TRIGGERS = [
    "was ruled out", "have been ruled out", "were ruled out",
    "were negative", "not present", "not seen", "not found",
    "not demonstrated", "not identified",
    "absent", "negative", "unlikely",
]

PSEUDO_NEGATION_TRIGGERS = [
    "not only", "no increase", "no change", "no decrease",
    "not cause", "not certain", "no reason", "not necessarily",
    "without difficulty", "without hesitation", "no further",
    "not rule out",
]

SCOPE_TERMINATORS_RE = re.compile(r"[.;\n]|\b(but|however|although|yet)\b", re.IGNORECASE)
SCOPE_WINDOW = 6


def _check_negation(sentence: str, concept: str) -> bool:
    sent_lower = sentence.lower()
    matches = list(re.finditer(r"\b" + re.escape(concept) + r"\b", sent_lower))
    if not matches:
        return False

    tokens = sent_lower.split()
    char_pos = 0
    token_starts = []
    for tok in tokens:
        token_starts.append(char_pos)
        char_pos += len(tok) + 1

    for match in matches:
        concept_start_char = match.start()
        concept_tok_idx = 0
        for i, ts in enumerate(token_starts):
            if ts <= concept_start_char:
                concept_tok_idx = i

        pre_text = " ".join(tokens[max(0, concept_tok_idx - SCOPE_WINDOW):concept_tok_idx])
        post_text = " ".join(tokens[concept_tok_idx + 1:
                                     min(len(tokens), concept_tok_idx + SCOPE_WINDOW + 1)])

        pre_scope = SCOPE_TERMINATORS_RE.search(pre_text)
        if pre_scope:
            pre_text = pre_text[pre_scope.end():]
        post_scope = SCOPE_TERMINATORS_RE.search(post_text)
        if post_scope:
            post_text = post_text[:post_scope.start()]

        local_context = pre_text + " " + post_text
        if any(p in local_context for p in PSEUDO_NEGATION_TRIGGERS):
            return False

        pre_negated  = any(t in pre_text  for t in PRE_NEGATION_TRIGGERS)
        post_negated = any(t in post_text for t in POST_NEGATION_TRIGGERS)

        if not pre_negated and not post_negated:
            return False

    return True


def is_concept_present(text: str, concept: str) -> int:
    text_lower = text.lower()
    if not re.search(r"\b" + re.escape(concept) + r"\b", text_lower):
        return 0
    for sentence in re.split(r"[.\n;]+", text_lower):
        sentence = sentence.strip()
        if not sentence:
            continue
        if not re.search(r"\b" + re.escape(concept) + r"\b", sentence):
            continue
        if not _check_negation(sentence, concept):
            return 1
    return 0


def generate_concept_labels(texts: list[str], concepts: list[str]) -> np.ndarray:
    labels = []
    for text in tqdm(texts, desc="  Concept labels", leave=False, mininterval=2.0):
        labels.append([is_concept_present(str(text), c) for c in concepts])
    return np.array(labels, dtype=np.float32)


def generate_naive_labels(texts: list[str], concepts: list[str]) -> np.ndarray:
    labels = []
    for text in tqdm(texts, desc="  Naive labels", leave=False, mininterval=2.0):
        tl = str(text).lower()
        labels.append([1 if re.search(r"\b" + re.escape(c) + r"\b", tl) else 0
                        for c in concepts])
    return np.array(labels, dtype=np.float32)


def log_negation_stats(raw: np.ndarray, negex: np.ndarray, concepts: list[str]) -> None:
    total_raw    = int(raw.sum())
    total_negex  = int(negex.sum())
    negated      = total_raw - total_negex
    rate         = (negated / max(total_raw, 1)) * 100
    print(f"\n{'='*60}")
    print("Negation Stats (train sample)")
    print(f"  Naive activations : {total_raw:,}")
    print(f"  NegEx activations : {total_negex:,}")
    print(f"  Negated           : {negated:,}  ({rate:.1f}%)")
    per_concept = (raw - negex).sum(axis=0)
    top10 = np.argsort(per_concept)[::-1][:10]
    print("\n  Top 10 most-negated concepts:")
    for idx in top10:
        print(f"    {concepts[idx]:<28s}  negated={int(per_concept[idx]):,}")
    print(f"{'='*60}\n")

# ============================================================================
# STEP 1: LOAD diagnoses_icd.csv.gz → TOP-50 ICD-10 CODES
#         (excluding non-clinical codes)
# ============================================================================

print("\n" + "="*60)
print("Step 1: Computing Top-50 ICD-10 codes (with exclusions)")
print("="*60)

assert DIAGNOSES_CSV.exists(), f"File not found: {DIAGNOSES_CSV}"
df_dx = pd.read_csv(DIAGNOSES_CSV, compression="gzip")
print(f"  Loaded diagnoses: {len(df_dx):,} rows")

df_dx10 = df_dx[df_dx["icd_version"] == 10].copy()
print(f"  ICD-10 rows: {len(df_dx10):,}")

df_dx10_unique = df_dx10.drop_duplicates(subset=["hadm_id", "icd_code"])
code_counts    = df_dx10_unique["icd_code"].value_counts()

# Exclude non-clinical codes, then take top 50
code_counts_filtered = code_counts[~code_counts.index.isin(CODES_TO_EXCLUDE)]
TOP_50_CODES  = code_counts_filtered.head(TOP_N).index.tolist()
TOP_50_COUNTS = code_counts_filtered.head(TOP_N).to_dict()

print(f"  Excluded codes: {sorted(CODES_TO_EXCLUDE)}")
print(f"  Top-{TOP_N} codes computed.")
print(f"  Top 5: {TOP_50_CODES[:5]}")

# Verify the bad codes are gone and replacements are in
for bad in CODES_TO_EXCLUDE:
    assert bad not in TOP_50_CODES, f"{bad} should have been excluded!"
for expected_new in ["E876", "E875", "D72829"]:
    status = "✓" if expected_new in TOP_50_CODES else "not in top 50 (check rank)"
    print(f"  Replacement {expected_new}: {status}")

top50_icd10_info = {
    "version":                       "v2.1",
    "total_admissions_in_diagnoses": int(df_dx10["hadm_id"].nunique()),
    "top_50_codes":                  TOP_50_CODES,
    "top_50_counts":                 {k: int(v) for k, v in TOP_50_COUNTS.items()},
    "excluded_codes":                sorted(CODES_TO_EXCLUDE),
}

# ============================================================================
# STEP 2: LOAD discharge.csv.gz
# ============================================================================

print("\n" + "="*60)
print("Step 2: Loading discharge.csv.gz")
print("="*60)

assert DISCHARGE_CSV.exists(), f"File not found: {DISCHARGE_CSV}"
df_notes = pd.read_csv(DISCHARGE_CSV, compression="gzip")
print(f"  Loaded notes: {len(df_notes):,} rows")

df_notes = df_notes[["hadm_id", "text"]].dropna(subset=["hadm_id", "text"]).copy()
df_notes["hadm_id"] = df_notes["hadm_id"].astype(int)
print(f"  Notes with hadm_id + text: {len(df_notes):,}")

# ============================================================================
# STEP 3: BUILD MULTI-HOT LABEL MATRIX
# ============================================================================

print("\n" + "="*60)
print("Step 3: Building multi-hot label matrix")
print("="*60)

top50_set = set(TOP_50_CODES)
dx_rows   = df_dx10_unique[df_dx10_unique["icd_code"].isin(top50_set)][["hadm_id", "icd_code"]]
dx_rows   = dx_rows.copy()
dx_rows["hadm_id"] = dx_rows["hadm_id"].astype(int)

dx_pivot  = dx_rows.assign(val=1).pivot_table(
    index="hadm_id", columns="icd_code", values="val", aggfunc="max", fill_value=0
)
dx_pivot  = dx_pivot.reindex(columns=TOP_50_CODES, fill_value=0).reset_index()
print(f"  Admissions with ≥1 top-50 code: {len(dx_pivot):,}")

# ============================================================================
# STEP 4: MERGE NOTES WITH LABELS
# ============================================================================

print("\n" + "="*60)
print("Step 4: Merging notes with labels")
print("="*60)

df_merged           = df_notes.merge(dx_pivot, on="hadm_id", how="inner")
df_merged["labels"] = df_merged[TOP_50_CODES].values.tolist()
df_final            = df_merged[["hadm_id", "text", "labels"] + TOP_50_CODES].reset_index(drop=True)
print(f"  Final dataset: {len(df_final):,} admissions")
top50_icd10_info["total_admissions_final"] = len(df_final)

# ============================================================================
# STEP 5: TRAIN / VAL / TEST SPLIT (70 / 15 / 15)
# ============================================================================

print("\n" + "="*60)
print("Step 5: Splitting 70/15/15")
print("="*60)

train_df, temp_df = train_test_split(df_final, test_size=0.30, random_state=SEED)
val_df,   test_df = train_test_split(temp_df,  test_size=0.50, random_state=SEED)

train_df = train_df.reset_index(drop=True)
val_df   = val_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

print(f"  Train: {len(train_df):,}  |  Val: {len(val_df):,}  |  Test: {len(test_df):,}")

split_info = {
    "train_size":  len(train_df),
    "val_size":    len(val_df),
    "test_size":   len(test_df),
    "num_labels":  TOP_N,
    "label_codes": TOP_50_CODES,
}

# ============================================================================
# STEP 6: NEGATION-AWARE CONCEPT LABELS (NegEx)
# ============================================================================

print("\n" + "="*60)
print(f"Step 6: Generating concept labels (NegEx, {len(GLOBAL_CONCEPTS)} concepts)")
print("="*60)

train_texts = train_df["text"].tolist()
val_texts   = val_df["text"].tolist()
test_texts  = test_df["text"].tolist()

print("  Generating train concept labels …")
train_concept_labels = generate_concept_labels(train_texts, GLOBAL_CONCEPTS)

print("  Generating val concept labels …")
val_concept_labels   = generate_concept_labels(val_texts,   GLOBAL_CONCEPTS)

print("  Generating test concept labels …")
test_concept_labels  = generate_concept_labels(test_texts,  GLOBAL_CONCEPTS)

print(f"  train_concept_labels shape: {train_concept_labels.shape}")
print(f"  Avg concepts per train sample: {train_concept_labels.sum(1).mean():.2f}  "
      f"(was ~18.25 with 111 concepts)")

# Negation stats on sample
print("\n  Computing negation stats (sample of 5000) …")
sample_idx  = np.random.choice(len(train_texts), size=min(5000, len(train_texts)), replace=False)
naive_sample = generate_naive_labels([train_texts[i] for i in sample_idx], GLOBAL_CONCEPTS)
negex_sample = train_concept_labels[sample_idx]
log_negation_stats(naive_sample, negex_sample, GLOBAL_CONCEPTS)

# ============================================================================
# STEP 7: TOKENIZER STATS (ModernBERT)
# ============================================================================

print("\n" + "="*60)
print("Step 7: Tokenizer stats (ModernBERT, sample=1000)")
print("="*60)

print(f"  Loading tokenizer: {MODEL_NAME}")
tokenizer   = AutoTokenizer.from_pretrained(MODEL_NAME)
sample_size = min(1000, len(train_texts))
sample_tok  = random.sample(train_texts, sample_size)

token_lengths = []
for txt in tqdm(sample_tok, desc="  Tokenizing sample", leave=False):
    ids = tokenizer(str(txt), truncation=False, add_special_tokens=True,
                    return_attention_mask=False)["input_ids"]
    token_lengths.append(len(ids))

token_lengths = np.array(token_lengths)
print(f"\n  Token length stats (n={sample_size}):")
print(f"    Mean   : {token_lengths.mean():.0f}")
print(f"    Median : {np.median(token_lengths):.0f}")
print(f"    p90    : {np.percentile(token_lengths, 90):.0f}")
print(f"    p95    : {np.percentile(token_lengths, 95):.0f}")
print(f"    % notes ≤ {MAX_LENGTH} tokens: {(token_lengths <= MAX_LENGTH).mean()*100:.1f}%")

# ============================================================================
# STEP 8: SAVE SPLITS, LABELS, METADATA TO DRIVE
# ============================================================================

print("\n" + "="*60)
print("Step 8: Saving splits, labels, metadata")
print("="*60)

with open(OUT_DIR / "train_split.pkl", "wb") as f: pickle.dump(train_df, f, protocol=4)
with open(OUT_DIR / "val_split.pkl",   "wb") as f: pickle.dump(val_df,   f, protocol=4)
with open(OUT_DIR / "test_split.pkl",  "wb") as f: pickle.dump(test_df,  f, protocol=4)
print("  Saved: train/val/test_split.pkl")

np.save(OUT_DIR / "train_concept_labels.npy", train_concept_labels)
np.save(OUT_DIR / "val_concept_labels.npy",   val_concept_labels)
np.save(OUT_DIR / "test_concept_labels.npy",  test_concept_labels)
print("  Saved: train/val/test_concept_labels.npy")

with open(OUT_DIR / "concept_list.json",      "w") as f: json.dump(GLOBAL_CONCEPTS,   f, indent=2)
with open(OUT_DIR / "top50_icd10_info.json",  "w") as f: json.dump(top50_icd10_info,  f, indent=2)
with open(OUT_DIR / "split_info.json",        "w") as f: json.dump(split_info,         f, indent=2)
print("  Saved: concept_list.json, top50_icd10_info.json, split_info.json")

# ============================================================================
# STEP 9: PRE-TOKENIZE ALL SPLITS AND SAVE TO DRIVE
# ============================================================================

print("\n" + "="*60)
print("Step 9: Pre-tokenizing all splits (eliminates DataLoader bottleneck)")
print("="*60)

TOK_BATCH = 64   # conservative at 6144 tokens per sample

def pretokenize(texts: list[str], desc: str) -> tuple[np.ndarray, np.ndarray]:
    all_ids, all_masks = [], []
    for i in tqdm(range(0, len(texts), TOK_BATCH), desc=f"  {desc}"):
        chunk = [str(t) for t in texts[i : i + TOK_BATCH]]
        enc   = tokenizer(chunk, max_length=MAX_LENGTH, padding="max_length", truncation=True)
        all_ids.append(np.array(enc["input_ids"],       dtype=np.int32))
        all_masks.append(np.array(enc["attention_mask"], dtype=np.uint8))
    return np.concatenate(all_ids), np.concatenate(all_masks)

train_ids, train_masks = pretokenize(train_df["text"].tolist(), "Train")
val_ids,   val_masks   = pretokenize(val_df["text"].tolist(),   "Val  ")
test_ids,  test_masks  = pretokenize(test_df["text"].tolist(),  "Test ")

np.save(OUT_DIR / "train_input_ids.npy",      train_ids)
np.save(OUT_DIR / "train_attention_mask.npy", train_masks)
np.save(OUT_DIR / "val_input_ids.npy",        val_ids)
np.save(OUT_DIR / "val_attention_mask.npy",   val_masks)
np.save(OUT_DIR / "test_input_ids.npy",       test_ids)
np.save(OUT_DIR / "test_attention_mask.npy",  test_masks)

total_gb = sum(a.nbytes for a in [train_ids, train_masks,
                                   val_ids, val_masks,
                                   test_ids, test_masks]) / 1e9
print(f"  Saved: *_input_ids.npy + *_attention_mask.npy  ({total_gb:.1f} GB total)")
print(f"  Shapes — train: {train_ids.shape}  val: {val_ids.shape}  test: {test_ids.shape}")

# ============================================================================
# DONE
# ============================================================================

print("\n" + "="*60)
print("v2.1/cell1_data.py complete.")
print(f"All outputs saved to: {OUT_DIR}")
print("="*60)
print(f"\nSummary:")
print(f"  Admissions          : {len(df_final):,}")
print(f"  Train / Val / Test  : {len(train_df):,} / {len(val_df):,} / {len(test_df):,}")
print(f"  ICD-10 codes        : {TOP_N}  (excluded: {sorted(CODES_TO_EXCLUDE)})")
print(f"  Concepts            : {len(GLOBAL_CONCEPTS)}")
print(f"  Max token length    : {MAX_LENGTH}")
print(f"\nNext: run v2.1/cell2_train.py")

"""## Cell 2"""

"""
cell2_train.py — ShifaMind v2.1 Phase 2: Model Definition & Training

Run AFTER v2.1/cell1_data.py. Reads preprocessed data from Google Drive,
trains the MCB model with BioClinical ModernBERT, saves best checkpoint.

Architecture: Pure Multiplicative Concept Bottleneck (MCB)
  - No GraphSAGE, no GAT, no RAG
  - BioClinical ModernBERT base (150M, 8192 tokens max)
  - Cross-attention concept grounding
  - Multiplicative gating bottleneck
"""

# ============================================================================
# IMPORTS & INSTALLS
# ============================================================================

import subprocess, sys

def pip_install(*packages):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])

pip_install("transformers", "scikit-learn")

# SDPA is used instead of flash-attn.
# No prebuilt flash-attn wheel exists for CUDA 12.8 + PyTorch 2.10 — it would
# compile from source (~20 min) on every runtime reset. PyTorch 2.10 SDPA is
# equally fast on modern NVIDIA GPUs and requires no extra install.
ATTN_IMPL = "sdpa"
print(f"Attention implementation: {ATTN_IMPL}")

import json
import pickle
import random
import numpy as np
import pandas as pd
from pathlib import Path
from collections import defaultdict

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score
from transformers import AutoModel, get_linear_schedule_with_warmup
from tqdm.auto import tqdm

# ============================================================================
# SEEDS & DEVICE
# ============================================================================

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

assert torch.cuda.is_available(), "GPU required. Please enable GPU runtime in Colab."
device = torch.device("cuda")
print(f"Device: {device} — {torch.cuda.get_device_name(0)}")
print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

# ============================================================================
# MOUNT GOOGLE DRIVE
# ============================================================================

try:
    from google.colab import drive
    drive.mount("/content/drive")
    print("Google Drive mounted.")
except ModuleNotFoundError:
    print("Not running in Colab — skipping Drive mount.")

# ============================================================================
# PATHS & CONFIG
# ============================================================================

DATA_DIR  = Path("/content/drive/MyDrive/ShifaMind_v2.1/data")
CKPT_DIR  = Path("/content/drive/MyDrive/ShifaMind_v2.1/checkpoints")
CKPT_DIR.mkdir(parents=True, exist_ok=True)

MODEL_NAME     = "thomas-sounack/BioClinical-ModernBERT-base"
MAX_LENGTH     = 6144
BATCH_SIZE     = 8
GRAD_ACCUM     = 1        # No accumulation needed with 95.6 GB VRAM
NUM_EPOCHS     = 5
LEARNING_RATE  = 2e-5
WEIGHT_DECAY   = 0.01
MAX_GRAD_NORM  = 1.0
WARMUP_RATIO   = 0.10

# Multi-task loss weights
LAMBDA_DIAG    = 2.0
LAMBDA_ALIGN   = 0.5
LAMBDA_CONCEPT = 0.3

# Focal loss (diagnosis head) — handles severe ICD-10 label imbalance
FOCAL_GAMMA = 2.0   # focusing exponent; 0 = standard BCE
FOCAL_ALPHA = 0.75  # positive-class weight

HIDDEN_SIZE    = 768
NUM_HEADS      = 8

# ============================================================================
# LOAD DATA FROM DRIVE
# ============================================================================

print("\n" + "="*60)
print("Loading preprocessed data from Drive")
print("="*60)

for p in [DATA_DIR / "train_split.pkl", DATA_DIR / "concept_list.json",
          DATA_DIR / "top50_icd10_info.json", DATA_DIR / "split_info.json"]:
    assert p.exists(), f"Missing: {p}\nRun cell1_data.py first."

with open(DATA_DIR / "train_split.pkl",  "rb") as f: df_train = pickle.load(f)
with open(DATA_DIR / "val_split.pkl",    "rb") as f: df_val   = pickle.load(f)
with open(DATA_DIR / "test_split.pkl",   "rb") as f: df_test  = pickle.load(f)

train_concept_labels = np.load(DATA_DIR / "train_concept_labels.npy")
val_concept_labels   = np.load(DATA_DIR / "val_concept_labels.npy")
test_concept_labels  = np.load(DATA_DIR / "test_concept_labels.npy")

with open(DATA_DIR / "concept_list.json")     as f: concept_list  = json.load(f)
with open(DATA_DIR / "top50_icd10_info.json") as f: top50_info    = json.load(f)
with open(DATA_DIR / "split_info.json")       as f: split_info    = json.load(f)

TOP_50_CODES  = top50_info["top_50_codes"]
NUM_LABELS    = len(TOP_50_CODES)
NUM_CONCEPTS  = len(concept_list)

print(f"  Train: {len(df_train):,}  |  Val: {len(df_val):,}  |  Test: {len(df_test):,}")
print(f"  ICD-10 labels: {NUM_LABELS}   Concepts: {NUM_CONCEPTS}")
print(f"  train_concept_labels: {train_concept_labels.shape}")

# Load pre-tokenized arrays produced by cell1 Step 9
print("\nLoading pre-tokenized arrays…")
for fname in ["train_input_ids.npy", "train_attention_mask.npy",
              "val_input_ids.npy",   "val_attention_mask.npy",
              "test_input_ids.npy",  "test_attention_mask.npy"]:
    assert (DATA_DIR / fname).exists(), f"Missing: {fname} — re-run cell1_data.py"

train_input_ids      = np.load(DATA_DIR / "train_input_ids.npy")
train_attention_mask = np.load(DATA_DIR / "train_attention_mask.npy")
val_input_ids        = np.load(DATA_DIR / "val_input_ids.npy")
val_attention_mask   = np.load(DATA_DIR / "val_attention_mask.npy")
test_input_ids       = np.load(DATA_DIR / "test_input_ids.npy")
test_attention_mask  = np.load(DATA_DIR / "test_attention_mask.npy")
print(f"  Loaded — train: {train_input_ids.shape}  val: {val_input_ids.shape}  test: {test_input_ids.shape}")

# ============================================================================
# DATASET  (no tokenization — arrays already prepared by cell1)
# ============================================================================

class ShifaMindDataset(Dataset):
    def __init__(self, input_ids, attention_mask, labels, concept_labels):
        self.input_ids       = input_ids        # np.ndarray [N, MAX_LENGTH] int32
        self.attention_mask  = attention_mask   # np.ndarray [N, MAX_LENGTH] uint8
        self.labels          = labels           # list of lists [0/1 × NUM_LABELS]
        self.concept_labels  = concept_labels   # np.ndarray [N, NUM_CONCEPTS]

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            "input_ids":        torch.from_numpy(self.input_ids[idx].astype(np.int64)),
            "attention_mask":   torch.from_numpy(self.attention_mask[idx].astype(np.int64)),
            "diagnosis_labels": torch.tensor(self.labels[idx],            dtype=torch.float32),
            "concept_labels":   torch.tensor(self.concept_labels[idx],    dtype=torch.float32),
        }


train_ds = ShifaMindDataset(
    train_input_ids, train_attention_mask,
    df_train["labels"].tolist(), train_concept_labels,
)
val_ds = ShifaMindDataset(
    val_input_ids, val_attention_mask,
    df_val["labels"].tolist(), val_concept_labels,
)
test_ds = ShifaMindDataset(
    test_input_ids, test_attention_mask,
    df_test["labels"].tolist(), test_concept_labels,
)

train_loader = DataLoader(
    train_ds, batch_size=BATCH_SIZE, shuffle=True,
    num_workers=4, pin_memory=True,
)
val_loader = DataLoader(
    val_ds, batch_size=BATCH_SIZE, shuffle=False,
    num_workers=4, pin_memory=True,
)
test_loader = DataLoader(
    test_ds, batch_size=BATCH_SIZE, shuffle=False,
    num_workers=4, pin_memory=True,
)
print(f"  Train batches: {len(train_loader)}  Val: {len(val_loader)}  Test: {len(test_loader)}")

# ============================================================================
# MODEL — Pure MCB with BioClinical ModernBERT
# ============================================================================

class ShifaMindMCB(nn.Module):
    """
    Multiplicative Concept Bottleneck (MCB) with BioClinical ModernBERT.

    Forward pass:
      1. ModernBERT encodes discharge summary → H [B, L, 768]
      2. CLS pool → pooled_text [B, 768]
      3. Concept embeddings attend to H (cross-attention) → Z_c [B, |C|, 768]
      4. Mean-pool Z_c → pooled_context [B, 768]  (concept-grounded text repr)
      5. Concept head predicts concept scores from pooled_text
      6. Gate net: [pooled_text ⊕ pooled_context] → gate [B, 768]
      7. Bottleneck = gate ⊙ pooled_context  (multiplicative — NOT additive)
      8. LayerNorm → diagnosis head → logits [B, 50]
    """

    def __init__(self, num_concepts: int, num_labels: int, attn_impl: str = "sdpa"):
        super().__init__()

        # --- Backbone --------------------------------------------------------
        self.encoder = AutoModel.from_pretrained(
            MODEL_NAME,
            attn_implementation=attn_impl,
        )

        # --- Concept embeddings (randomly initialised, trained end-to-end) ---
        self.concept_embeddings = nn.Embedding(num_concepts, HIDDEN_SIZE)
        nn.init.xavier_uniform_(self.concept_embeddings.weight)

        # --- Cross-attention: concept queries attend to token keys/values ----
        # Q = concept embeddings [B, |C|, 768]
        # K = V = token representations H [B, L, 768]
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=HIDDEN_SIZE,
            num_heads=NUM_HEADS,
            batch_first=True,
            dropout=0.1,
        )

        # --- Concept head: text pool → concept logits [B, |C|] ---------------
        self.concept_head = nn.Linear(HIDDEN_SIZE, num_concepts)

        # --- Gate network: [pooled_text ⊕ pooled_context] → gate [B, 768] ---
        # Two-layer MLP: 1536 → 768 (ReLU) → 768 (Sigmoid)
        self.gate_net = nn.Sequential(
            nn.Linear(HIDDEN_SIZE * 2, HIDDEN_SIZE),
            nn.ReLU(),
            nn.Linear(HIDDEN_SIZE, HIDDEN_SIZE),
            nn.Sigmoid(),
        )

        # --- Bottleneck LayerNorm -------------------------------------------
        self.bottleneck_norm = nn.LayerNorm(HIDDEN_SIZE)

        # --- Diagnosis head: bottleneck → diagnosis logits [B, 50] -----------
        self.diagnosis_head = nn.Linear(HIDDEN_SIZE, num_labels)

    def forward(self, input_ids, attention_mask):
        B = input_ids.size(0)

        # 1. Encode text
        enc_out = self.encoder(
            input_ids=input_ids,
            attention_mask=attention_mask,
        )
        H = enc_out.last_hidden_state  # [B, L, 768]

        # 2. CLS token pool
        pooled_text = H[:, 0, :]  # [B, 768]

        # 3. Cross-attention: concepts attend to tokens
        #    key_padding_mask: True = ignore (padding), False = attend (real token)
        key_padding_mask = (attention_mask == 0)  # [B, L]

        concept_queries = self.concept_embeddings.weight.unsqueeze(0).expand(B, -1, -1)
        # [B, num_concepts, 768]

        Z_c, _ = self.cross_attn(
            query=concept_queries,
            key=H,
            value=H,
            key_padding_mask=key_padding_mask,
        )
        # Z_c: [B, num_concepts, 768] — each concept grounded to relevant tokens

        # 4. Mean-pool concept representations → context vector
        pooled_context = Z_c.mean(dim=1)  # [B, 768]

        # 5. Concept logits (from text pool, not from Z_c — fast, sufficient)
        concept_logits = self.concept_head(pooled_text)  # [B, num_concepts]

        # 6. Gate: combine text and concept-grounded representations
        gate_input = torch.cat([pooled_text, pooled_context], dim=-1)  # [B, 1536]
        gate = self.gate_net(gate_input)                                 # [B, 768]

        # 7. Multiplicative bottleneck (NOT additive — preserves interpretability)
        bottleneck = gate * pooled_context     # [B, 768]
        bottleneck = self.bottleneck_norm(bottleneck)

        # 8. Diagnosis logits
        diagnosis_logits = self.diagnosis_head(bottleneck)  # [B, 50]

        return {
            "diagnosis_logits": diagnosis_logits,    # [B, num_labels]
            "concept_logits":   concept_logits,      # [B, num_concepts]
            "concept_repr":     pooled_context,      # [B, 768] — for alignment loss
            "text_repr":        pooled_text,         # [B, 768] — for alignment loss
        }


# ============================================================================
# LOSS
# ============================================================================

def focal_loss(logits, targets, gamma=FOCAL_GAMMA, alpha=FOCAL_ALPHA):
    """
    Sigmoid Focal Loss for multi-label classification.
    Handles class imbalance by down-weighting easy examples.
      FL = -alpha * (1 - p)^gamma * log(p)       for positives
         - (1-alpha) * p^gamma * log(1-p)         for negatives
    """
    bce = F.binary_cross_entropy_with_logits(logits, targets, reduction="none")
    p_t = torch.exp(-bce)                           # probability of correct class
    alpha_t = alpha * targets + (1 - alpha) * (1 - targets)
    focal_weight = alpha_t * (1 - p_t) ** gamma
    return (focal_weight * bce).mean()


def compute_loss(outputs, diagnosis_labels, concept_labels):
    """
    Multi-task loss:
      L = λ_diag * L_diag + λ_align * L_align + λ_concept * L_concept

      L_diag    = FocalLoss(γ=2, α=0.75) — handles ICD-10 label imbalance
      L_concept = BCE(concept_logits, concept_labels)
      L_align   = 1 - cosine_similarity(concept_repr, text_repr).mean()
    """
    L_diag = focal_loss(outputs["diagnosis_logits"], diagnosis_labels)
    L_concept = F.binary_cross_entropy_with_logits(
        outputs["concept_logits"], concept_labels
    )
    L_align = (
        1.0 - F.cosine_similarity(
            outputs["concept_repr"], outputs["text_repr"], dim=-1
        ).mean()
    )

    total = LAMBDA_DIAG * L_diag + LAMBDA_ALIGN * L_align + LAMBDA_CONCEPT * L_concept

    return total, {
        "total":   total.item(),
        "diag":    L_diag.item(),
        "concept": L_concept.item(),
        "align":   L_align.item(),
    }


# ============================================================================
# EVALUATION
# ============================================================================

@torch.no_grad()
def evaluate(model, loader, desc="Val"):
    model.eval()
    all_logits, all_labels = [], []

    for batch in tqdm(loader, desc=f"  {desc}", leave=False):
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        dx_labels      = batch["diagnosis_labels"]

        with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
            out = model(input_ids, attention_mask)
        all_logits.append(torch.sigmoid(out["diagnosis_logits"]).float().cpu().numpy())
        all_labels.append(dx_labels.numpy())

    probs  = np.vstack(all_logits)   # [N, NUM_LABELS]
    labels = np.vstack(all_labels)   # [N, NUM_LABELS]
    preds  = (probs > 0.5).astype(int)

    macro_f1 = float(f1_score(labels, preds, average="macro",  zero_division=0))
    micro_f1 = float(f1_score(labels, preds, average="micro",  zero_division=0))

    model.train()
    return macro_f1, micro_f1, probs, labels


# ============================================================================
# BUILD MODEL
# ============================================================================

print("\n" + "="*60)
print("Building ShifaMind MCB model")
print("="*60)

print(f"  Attention implementation: {ATTN_IMPL}")

model = ShifaMindMCB(
    num_concepts=NUM_CONCEPTS,
    num_labels=NUM_LABELS,
    attn_impl=ATTN_IMPL,
).to(device)

total_params     = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"  Total params:     {total_params:,}")
print(f"  Trainable params: {trainable_params:,}")

# ============================================================================
# OPTIMIZER & SCHEDULER
# ============================================================================

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

num_optimizer_steps = (len(train_loader) // GRAD_ACCUM) * NUM_EPOCHS
num_warmup_steps    = int(num_optimizer_steps * WARMUP_RATIO)

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=num_warmup_steps,
    num_training_steps=num_optimizer_steps,
)

print(f"\n  Optimizer:       AdamW  lr={LEARNING_RATE}  wd={WEIGHT_DECAY}")
print(f"  Total steps:     {num_optimizer_steps:,}")
print(f"  Warmup steps:    {num_warmup_steps:,}  ({WARMUP_RATIO*100:.0f}%)")
print(f"  Epochs:          {NUM_EPOCHS}")
print(f"  Batch size:      {BATCH_SIZE}  (grad_accum={GRAD_ACCUM})")
print(f"  Max seq length:  {MAX_LENGTH}")

# ============================================================================
# TRAINING LOOP
# ============================================================================

print("\n" + "="*60)
print("Training")
print("="*60)

best_val_macro_f1 = 0.0
training_log      = []

for epoch in range(NUM_EPOCHS):
    model.train()
    epoch_losses = defaultdict(list)

    optimizer.zero_grad()
    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{NUM_EPOCHS}", leave=True)

    for step, batch in enumerate(pbar):
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        dx_labels      = batch["diagnosis_labels"].to(device)
        c_labels       = batch["concept_labels"].to(device)

        with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
            outputs = model(input_ids, attention_mask)
            loss, components = compute_loss(outputs, dx_labels, c_labels)

        (loss / GRAD_ACCUM).backward()

        if (step + 1) % GRAD_ACCUM == 0 or (step + 1) == len(train_loader):
            torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()

        for k, v in components.items():
            epoch_losses[k].append(v)

        pbar.set_postfix(
            loss=f"{components['total']:.4f}",
            diag=f"{components['diag']:.4f}",
            lr=f"{scheduler.get_last_lr()[0]:.2e}",
        )

    avg_losses = {k: float(np.mean(v)) for k, v in epoch_losses.items()}
    current_lr = scheduler.get_last_lr()[0]

    print(f"\nEpoch {epoch+1} train — "
          f"total={avg_losses['total']:.4f}  "
          f"diag={avg_losses['diag']:.4f}  "
          f"align={avg_losses['align']:.4f}  "
          f"concept={avg_losses['concept']:.4f}  "
          f"lr={current_lr:.2e}")

    # --- Validation ----------------------------------------------------------
    val_macro_f1, val_micro_f1, _, _ = evaluate(model, val_loader, desc="Validating")
    print(f"Epoch {epoch+1} val   — macro_f1={val_macro_f1:.4f}  micro_f1={val_micro_f1:.4f}")

    training_log.append({
        "epoch":         epoch + 1,
        "train_loss":    avg_losses["total"],
        "train_diag":    avg_losses["diag"],
        "train_align":   avg_losses["align"],
        "train_concept": avg_losses["concept"],
        "val_macro_f1":  val_macro_f1,
        "val_micro_f1":  val_micro_f1,
        "lr":            current_lr,
    })

    # --- Save best checkpoint ------------------------------------------------
    if val_macro_f1 > best_val_macro_f1:
        best_val_macro_f1 = val_macro_f1
        ckpt_path = CKPT_DIR / "best_model.pt"
        torch.save({
            "model_state_dict": model.state_dict(),
            "epoch":            epoch + 1,
            "val_macro_f1":     val_macro_f1,
            "val_micro_f1":     val_micro_f1,
            "config": {
                "model_name":   MODEL_NAME,
                "num_concepts": NUM_CONCEPTS,
                "num_labels":   NUM_LABELS,
                "max_length":   MAX_LENGTH,
                "hidden_size":  HIDDEN_SIZE,
                "num_heads":    NUM_HEADS,
                "attn_impl":    ATTN_IMPL,
                "top_50_codes": TOP_50_CODES,
                "concept_list": concept_list,
            },
        }, ckpt_path)
        print(f"  *** New best val macro_f1={val_macro_f1:.4f} — checkpoint saved ***")

    # --- VRAM usage ----------------------------------------------------------
    allocated = torch.cuda.memory_allocated(device) / 1e9
    reserved  = torch.cuda.memory_reserved(device) / 1e9
    print(f"  VRAM: {allocated:.1f} GB allocated / {reserved:.1f} GB reserved")

# ============================================================================
# SAVE TRAINING LOG
# ============================================================================

log_path = CKPT_DIR / "training_log.json"
with open(log_path, "w") as f:
    json.dump(training_log, f, indent=2)
print(f"\nTraining log saved → {log_path}")

# ============================================================================
# DONE
# ============================================================================

print("\n" + "="*60)
print("cell2_train.py complete.")
print(f"  Best val Macro-F1: {best_val_macro_f1:.4f}")
print(f"  Checkpoint:        {CKPT_DIR / 'best_model.pt'}")
print(f"  Training log:      {log_path}")
print("="*60)
print("\nNext: run v2.1/cell3_evaluate.py")

"""## Cell 3"""

"""
cell3_evaluate.py — ShifaMind v2.1 Phase 3: Evaluation & Threshold Tuning

Run AFTER v2.1/cell2_train.py. Loads the best checkpoint, runs inference on
val + test sets, tunes thresholds on val (never test), evaluates on test
with three strategies: fixed 0.5, tuned global, tuned per-label.

Outputs (all saved to Drive):
  results/test_results.json         — all metrics at all threshold strategies
  results/per_label_f1.csv          — per-ICD-code F1 breakdown
  results/test_probabilities.npy    — raw test probabilities [N_test, 50]
  results/optimal_thresholds.json   — best global + per-label thresholds
"""

# ============================================================================
# IMPORTS & INSTALLS
# ============================================================================

import subprocess, sys

def pip_install(*packages):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])

pip_install("transformers", "scikit-learn")

import json
import pickle
import random
import numpy as np
import pandas as pd
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score, precision_score, recall_score
from transformers import AutoModel
from tqdm.auto import tqdm

# ============================================================================
# SEEDS & DEVICE
# ============================================================================

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

assert torch.cuda.is_available(), "GPU required."
device = torch.device("cuda")
print(f"Device: {device} — {torch.cuda.get_device_name(0)}")

# ============================================================================
# MOUNT GOOGLE DRIVE
# ============================================================================

try:
    from google.colab import drive
    drive.mount("/content/drive")
    print("Google Drive mounted.")
except ModuleNotFoundError:
    print("Not running in Colab — skipping Drive mount.")

# ============================================================================
# PATHS
# ============================================================================

BASE_DIR  = Path("/content/drive/MyDrive/ShifaMind_v2.1")
DATA_DIR  = BASE_DIR / "data"
CKPT_DIR  = BASE_DIR / "checkpoints"
OUT_DIR   = BASE_DIR / "results"
OUT_DIR.mkdir(parents=True, exist_ok=True)

CKPT_PATH = CKPT_DIR / "best_model.pt"
assert CKPT_PATH.exists(), f"Checkpoint not found: {CKPT_PATH}\nRun cell2_train.py first."

# ============================================================================
# LOAD CHECKPOINT & CONFIG
# ============================================================================

print("\n" + "="*60)
print("Loading checkpoint")
print("="*60)

ckpt   = torch.load(CKPT_PATH, map_location="cpu", weights_only=False)
config = ckpt["config"]

MODEL_NAME   = config["model_name"]
NUM_CONCEPTS = config["num_concepts"]
NUM_LABELS   = config["num_labels"]
MAX_LENGTH   = config["max_length"]
HIDDEN_SIZE  = config["hidden_size"]
NUM_HEADS    = config["num_heads"]
ATTN_IMPL    = config["attn_impl"]
TOP_50_CODES = config["top_50_codes"]
concept_list = config["concept_list"]

print(f"  Checkpoint epoch:    {ckpt['epoch']}")
print(f"  Val Macro-F1:        {ckpt['val_macro_f1']:.4f}")
print(f"  Val Micro-F1:        {ckpt['val_micro_f1']:.4f}")
print(f"  Model:               {MODEL_NAME}")
print(f"  Max length:          {MAX_LENGTH}")
print(f"  Num concepts:        {NUM_CONCEPTS}")
print(f"  Num labels:          {NUM_LABELS}")

# ============================================================================
# LOAD DATA FROM DRIVE
# ============================================================================

print("\n" + "="*60)
print("Loading data from Drive")
print("="*60)

with open(DATA_DIR / "val_split.pkl",  "rb") as f: df_val  = pickle.load(f)
with open(DATA_DIR / "test_split.pkl", "rb") as f: df_test = pickle.load(f)
with open(DATA_DIR / "top50_icd10_info.json") as f: top50_info = json.load(f)

# Pre-tokenized arrays
val_input_ids      = np.load(DATA_DIR / "val_input_ids.npy")
val_attention_mask = np.load(DATA_DIR / "val_attention_mask.npy")
test_input_ids     = np.load(DATA_DIR / "test_input_ids.npy")
test_attention_mask= np.load(DATA_DIR / "test_attention_mask.npy")

# Ground-truth label matrices
val_labels  = np.array(df_val["labels"].tolist(),  dtype=np.float32)  # [N_val,  50]
test_labels = np.array(df_test["labels"].tolist(), dtype=np.float32)  # [N_test, 50]

print(f"  Val:  {val_input_ids.shape}  labels: {val_labels.shape}")
print(f"  Test: {test_input_ids.shape}  labels: {test_labels.shape}")

# ============================================================================
# DATASET & LOADER
# ============================================================================

BATCH_SIZE = 8

class InferenceDataset(Dataset):
    def __init__(self, input_ids, attention_mask):
        self.input_ids      = input_ids
        self.attention_mask = attention_mask

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            "input_ids":      torch.from_numpy(self.input_ids[idx].astype(np.int64)),
            "attention_mask": torch.from_numpy(self.attention_mask[idx].astype(np.int64)),
        }

val_loader  = DataLoader(InferenceDataset(val_input_ids,  val_attention_mask),
                         batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True)
test_loader = DataLoader(InferenceDataset(test_input_ids, test_attention_mask),
                         batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True)

# ============================================================================
# MODEL DEFINITION (must match cell2 exactly)
# ============================================================================

class ShifaMindMCB(nn.Module):
    def __init__(self, num_concepts: int, num_labels: int, attn_impl: str = "sdpa"):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(MODEL_NAME, attn_implementation=attn_impl)
        self.concept_embeddings = nn.Embedding(num_concepts, HIDDEN_SIZE)
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=HIDDEN_SIZE, num_heads=NUM_HEADS, batch_first=True, dropout=0.1,
        )
        self.concept_head   = nn.Linear(HIDDEN_SIZE, num_concepts)
        self.gate_net = nn.Sequential(
            nn.Linear(HIDDEN_SIZE * 2, HIDDEN_SIZE),
            nn.ReLU(),
            nn.Linear(HIDDEN_SIZE, HIDDEN_SIZE),
            nn.Sigmoid(),
        )
        self.bottleneck_norm = nn.LayerNorm(HIDDEN_SIZE)
        self.diagnosis_head  = nn.Linear(HIDDEN_SIZE, num_labels)

    def forward(self, input_ids, attention_mask):
        B = input_ids.size(0)
        H = self.encoder(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state
        pooled_text      = H[:, 0, :]
        key_padding_mask = (attention_mask == 0)
        concept_queries  = self.concept_embeddings.weight.unsqueeze(0).expand(B, -1, -1)
        Z_c, _           = self.cross_attn(concept_queries, H, H,
                                           key_padding_mask=key_padding_mask)
        pooled_context   = Z_c.mean(dim=1)
        gate             = self.gate_net(torch.cat([pooled_text, pooled_context], dim=-1))
        bottleneck       = self.bottleneck_norm(gate * pooled_context)
        return self.diagnosis_head(bottleneck)   # [B, num_labels]

# ============================================================================
# BUILD MODEL & LOAD WEIGHTS
# ============================================================================

print("\n" + "="*60)
print("Building model & loading weights")
print("="*60)

model = ShifaMindMCB(NUM_CONCEPTS, NUM_LABELS, ATTN_IMPL).to(device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()
print(f"  Weights loaded. Parameters: {sum(p.numel() for p in model.parameters()):,}")

# ============================================================================
# INFERENCE HELPER
# ============================================================================

@torch.no_grad()
def run_inference(loader, desc="Inference"):
    """Returns float32 probability array [N, NUM_LABELS]."""
    all_probs = []
    for batch in tqdm(loader, desc=f"  {desc}"):
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
            logits = model(input_ids, attention_mask)
        all_probs.append(torch.sigmoid(logits).float().cpu().numpy())
    return np.vstack(all_probs)   # [N, NUM_LABELS]

# ============================================================================
# RUN INFERENCE
# ============================================================================

print("\n" + "="*60)
print("Running inference")
print("="*60)

val_probs  = run_inference(val_loader,  desc="Val  ")
test_probs = run_inference(test_loader, desc="Test ")

print(f"  val_probs  shape: {val_probs.shape}")
print(f"  test_probs shape: {test_probs.shape}")

# Save raw test probabilities immediately
np.save(OUT_DIR / "test_probabilities.npy", test_probs)
print(f"  Saved: test_probabilities.npy")

# ============================================================================
# THRESHOLD TUNING ON VALIDATION SET
# Never touch the test set during tuning.
# ============================================================================

print("\n" + "="*60)
print("Threshold tuning on validation set")
print("="*60)

THRESHOLDS = [round(t, 2) for t in np.arange(0.05, 1.00, 0.05)]

# --- Global threshold sweep ------------------------------------------------
print("  Global threshold sweep…")
global_results = []
for t in tqdm(THRESHOLDS, desc="  Global sweep", leave=False):
    preds    = (val_probs > t).astype(int)
    macro_f1 = float(f1_score(val_labels, preds, average="macro", zero_division=0))
    micro_f1 = float(f1_score(val_labels, preds, average="micro", zero_division=0))
    global_results.append({"threshold": t, "macro_f1": macro_f1, "micro_f1": micro_f1})

best_global = max(global_results, key=lambda x: x["macro_f1"])
GLOBAL_THRESH = best_global["threshold"]
print(f"  Best global threshold: {GLOBAL_THRESH}  →  val macro_f1={best_global['macro_f1']:.4f}")

# --- Per-label threshold sweep ---------------------------------------------
print("  Per-label threshold sweep…")
per_label_thresholds = []
for i in tqdm(range(NUM_LABELS), desc="  Per-label sweep", leave=False):
    best_t, best_f1 = 0.5, 0.0
    for t in THRESHOLDS:
        preds_i = (val_probs[:, i] > t).astype(int)
        f1_i    = float(f1_score(val_labels[:, i], preds_i, zero_division=0))
        if f1_i > best_f1:
            best_f1, best_t = f1_i, t
    per_label_thresholds.append(best_t)

per_label_thresh_array = np.array(per_label_thresholds)   # [NUM_LABELS]
print(f"  Per-label thresholds — min={per_label_thresh_array.min():.2f}  "
      f"max={per_label_thresh_array.max():.2f}  "
      f"mean={per_label_thresh_array.mean():.2f}")

# Save optimal thresholds
optimal_thresholds = {
    "global_threshold":     GLOBAL_THRESH,
    "global_val_macro_f1":  best_global["macro_f1"],
    "per_label_thresholds": dict(zip(TOP_50_CODES, [float(t) for t in per_label_thresholds])),
    "threshold_sweep":      global_results,
}
with open(OUT_DIR / "optimal_thresholds.json", "w") as f:
    json.dump(optimal_thresholds, f, indent=2)
print(f"  Saved: optimal_thresholds.json")

# ============================================================================
# EVALUATE ON TEST SET — THREE STRATEGIES
# ============================================================================

print("\n" + "="*60)
print("Evaluating on test set")
print("="*60)

def evaluate_with_preds(probs, labels, preds, label_codes, top50_counts):
    macro_f1  = float(f1_score(labels, preds, average="macro",  zero_division=0))
    micro_f1  = float(f1_score(labels, preds, average="micro",  zero_division=0))
    precision = float(precision_score(labels, preds, average="macro", zero_division=0))
    recall    = float(recall_score(labels, preds, average="macro",    zero_division=0))
    per_class = [float(f1_score(labels[:, i], preds[:, i], zero_division=0))
                 for i in range(labels.shape[1])]
    return {
        "macro_f1":    macro_f1,
        "micro_f1":    micro_f1,
        "precision":   precision,
        "recall":      recall,
        "per_class_f1": dict(zip(label_codes, per_class)),
    }

top50_counts = top50_info.get("top_50_counts", {})

# Strategy 1: fixed threshold = 0.5
preds_fixed      = (test_probs > 0.50).astype(int)
metrics_fixed    = evaluate_with_preds(test_probs, test_labels, preds_fixed,
                                        TOP_50_CODES, top50_counts)

# Strategy 2: tuned global threshold
preds_global     = (test_probs > GLOBAL_THRESH).astype(int)
metrics_global   = evaluate_with_preds(test_probs, test_labels, preds_global,
                                        TOP_50_CODES, top50_counts)

# Strategy 3: tuned per-label thresholds
preds_per_label  = (test_probs > per_label_thresh_array[None, :]).astype(int)
metrics_per_label= evaluate_with_preds(test_probs, test_labels, preds_per_label,
                                        TOP_50_CODES, top50_counts)

# ============================================================================
# SUMMARY TABLE
# ============================================================================

print("\n" + "="*60)
print("Test Set Results")
print("="*60)
print(f"  {'Strategy':<25s}  {'Macro-F1':>9}  {'Micro-F1':>9}  {'Precision':>9}  {'Recall':>9}")
print(f"  {'-'*25}  {'-'*9}  {'-'*9}  {'-'*9}  {'-'*9}")
for name, m in [
    ("Fixed (0.50)",       metrics_fixed),
    (f"Global ({GLOBAL_THRESH:.2f})", metrics_global),
    ("Per-label",          metrics_per_label),
]:
    print(f"  {name:<25s}  {m['macro_f1']:>9.4f}  {m['micro_f1']:>9.4f}  "
          f"{m['precision']:>9.4f}  {m['recall']:>9.4f}")
print("="*60)

# ============================================================================
# PER-LABEL F1 BREAKDOWN
# ============================================================================

print(f"\n  Per-label F1 (per-label threshold strategy, all {NUM_LABELS} codes):")
print(f"  {'ICD Code':<12}  {'Threshold':>9}  {'F1':>7}  {'Train count':>12}")
print(f"  {'-'*12}  {'-'*9}  {'-'*7}  {'-'*12}")

per_label_rows = []
for i, code in enumerate(TOP_50_CODES):
    f1_val  = metrics_per_label["per_class_f1"][code]
    thresh  = per_label_thresholds[i]
    count   = int(top50_counts.get(code, 0))
    per_label_rows.append({
        "icd_code":    code,
        "threshold":   thresh,
        "f1_fixed":    metrics_fixed["per_class_f1"][code],
        "f1_global":   metrics_global["per_class_f1"][code],
        "f1_per_label":f1_val,
        "train_count": count,
    })

per_label_df = (
    pd.DataFrame(per_label_rows)
      .sort_values("f1_per_label", ascending=False)
      .reset_index(drop=True)
)
for _, row in per_label_df.iterrows():
    print(f"  {row['icd_code']:<12}  {row['threshold']:>9.2f}  "
          f"{row['f1_per_label']:>7.4f}  {int(row['train_count']):>12,}")

# ============================================================================
# SAVE ALL RESULTS
# ============================================================================

print("\n" + "="*60)
print("Saving results")
print("="*60)

test_results = {
    "model":             MODEL_NAME,
    "checkpoint_epoch":  ckpt["epoch"],
    "val_macro_f1":      ckpt["val_macro_f1"],
    "dataset": {
        "val_size":  len(df_val),
        "test_size": len(df_test),
        "num_labels": NUM_LABELS,
    },
    "fixed_threshold": {
        "threshold": 0.50,
        **{k: v for k, v in metrics_fixed.items() if k != "per_class_f1"},
    },
    "global_threshold": {
        "threshold": GLOBAL_THRESH,
        **{k: v for k, v in metrics_global.items() if k != "per_class_f1"},
    },
    "per_label_threshold": {
        **{k: v for k, v in metrics_per_label.items() if k != "per_class_f1"},
    },
    "per_class_f1": {
        "fixed":     metrics_fixed["per_class_f1"],
        "global":    metrics_global["per_class_f1"],
        "per_label": metrics_per_label["per_class_f1"],
    },
}

with open(OUT_DIR / "test_results.json", "w") as f:
    json.dump(test_results, f, indent=2)

per_label_df.to_csv(OUT_DIR / "per_label_f1.csv", index=False)

print(f"  Saved: test_results.json")
print(f"  Saved: per_label_f1.csv")
print(f"  Saved: test_probabilities.npy  (already saved above)")
print(f"  Saved: optimal_thresholds.json (already saved above)")

# ============================================================================
# DONE
# ============================================================================

print("\n" + "="*60)
print("cell3_evaluate.py complete.")
print("="*60)
print(f"\n  Best test Macro-F1 (per-label): {metrics_per_label['macro_f1']:.4f}")
print(f"  Best test Macro-F1 (global):    {metrics_global['macro_f1']:.4f}")
print(f"  Best test Macro-F1 (fixed 0.5): {metrics_fixed['macro_f1']:.4f}")
print(f"\n  Results → {OUT_DIR}")